# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161017_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printjobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
