# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161017_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='file_uploaded',
            field=models.FileField(default='default.png', upload_to=''),
            preserve_default=False,
        ),
    ]
