# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_printjob_file_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='last_printed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
