# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161021_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('has_completed', models.BooleanField(default=False)),
                ('print_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printruns', to='api.PrintJob')),
            ],
        ),
    ]
